---
- hosts: all
  become: yes
  become_user: root
  user: ubuntu
  tasks:
    - name: Update repositories cache and install "docker-compose" package
      apt:
        name: docker-compose
        state: present # declerative
        update_cache: yes